apiVersion: v1
kind: Service
metadata:
  name: greenhouse-monitor-service
  namespace: greenhouse-monitoring
  labels:
    app: greenhouse-monitor
spec:
  type: NodePort
  selector:
    app: greenhouse-monitor
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30080

